### ISSUE TITLE
hls-video-element is broken on latest node@22

### ISSUE THREAD

**Issue by JinxedStar** [muxinc/media-elements#56]
In our project we've been using hls-video-element successfully, and I just got a new m4 Macbook Pro! After installing everything, I was unable to run our node app, and was pulling my hair out wondering what the heck was going on with this error msg when running `yarn web`:

```
ReferenceError: require is not defined
    at file:///Users/jinxedstar/Documents/GitHub/MYPROJECT/node_modules/hls.js/dist/hls.mjs:1:46
    at ModuleJobSync.runSync (node:internal/modules/esm/module_job:341:35)
    at ModuleLoader.importSyncForRequire (node:internal/modules/esm/loader:317:47)
    at loadESMFromCJS (node:internal/modules/cjs/loader:1381:24)
    at Module._compile (node:internal/modules/cjs/loader:1503:5)
    at Module._compile (/Users/jinxedstar/Documents/GitHub/MYPROJECT/node_modules/esbuild-register/dist/node.js:2258:26)
    at Module._extensions..js (node:internal/modules/cjs/loader:1691:10)
    at Object.newLoader (/Users/jinxedstar/Documents/GitHub/MYPROJECT/node_modules/esbuild-register/dist/node.js:2262:9)
    at Module.load (node:internal/modules/cjs/loader:1317:32)
    at Module._load (node:internal/modules/cjs/loader:1127:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1339:12)
    at mod.require (/Users/jinxedstar/Documents/GitHub/MYPROJECT/node_modules/next/dist/server/require-hook.js:65:28)
    at Module.tamaguiRequire (/Users/jinxedstar/Documents/GitHub/MYPROJECT/node_modules/@tamagui/static/dist/registerRequire.js:66:17)

... 100s lines of same error crap omitted
```

And after some serious fooling around with configs and node versions and etc, I finally tracked it down! Our app was running on Node 22.3.0 and for some reason nvm ignored the pinned version, and installed 22.11.0 on my machine. I downgraded to 22.9.0 and it was still broken, so I gave up and did a full downgrade to 22.3.0 and verified that it worked A-OK.

This means the package is broken somewhere between 22.3 and 22.9, I don't have the time to further test this and find out why, sorry!

Our app currently uses hls-video-element v1.2.7, and I verified that it's still broken in v1.2.11, drats...

**Comment by wesbos** [comment]
Looking at your stacktrace, I think this is an issue with Next.js or Tamagui - Next still uses commonJS (even if it looks like you are writing ESM) and Node has been rolling out some features to allow for importing ESM from CJS. Try update your next.js version

**Comment by luwes** [comment]
Closing until more reports come in. Thanks for the feedback y'all!
